board/urls.py
from django.conf.urls import url

from board.views import *

urlpatterns = [
    # Example: /
    url(r'^$', PostList.as_view(), name='index'),

    # Example: /board/?page=3
    # 참고 https://goo.gl/BRFiJV
    # view에 paginate_by가 지정되어 있는 경우 페이지 객체수를 전달한다.
    url(r'^postlist/page(?P<page>[0-9]+)/$', PostList.as_view(), name='post_list'),

    # # Example: /post/add/
    url(r'^post/add/$', PostCreate.as_view(), name="post_add",),

    # Example: /post/99/
    url(r'^post/(?P<pk>\d+)/$', PostDetail.as_view(), name='post_detail'),

    # # Example: /post/99/update/
    # url(r'^post/(?P<pk>[0-9]+)/update/$', PostUpdate.as_view(), name="post_update",),

    # # Example: /post/99/delete/
    # url(r'^post/(?P<pk>[0-9]+)/delete/$', PostDelete.as_view(), name="post_delete",),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from mysite.views import HomeView
from mysite.views import UserRegisterView, UserRegisterDoneView

from mysite import views 

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserRegisterView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserRegisterDoneView.as_view(), name='register_done'),
    # ajax 는 ajax/로 시작하여 구분합니다.
    url(r'^ajax/validate_username/$', views.validate_username, name="validate_username"),


    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^board/', include('board.urls', namespace='board')),
]

board/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField('Content', blank=True)
    # https://goo.gl/GKVaAa 처음 생성될때 자동으로 현재 시간을 설정
    create_date = models.DateTimeField('Create Date', auto_now_add=True)
    # https://goo.gl/GKVaAa 매번 저장될때 자동으로 현재 시간을 설정
    modify_date = models.DateTimeField('Modify Date', auto_now=True)
    owner = models.ForeignKey(User, null=True)
        
    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table  = 'board_posts'
        ordering  = ('-create_date',)
        
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # reverse에서 인자로 리스트를 전달하고자 하는 경우는 args=[1,5]
        return reverse('board:post_detail', kwargs={'pk':self.id})

    def get_previous_post(self):
        # get_previous_by_<필드명> 메서드
        try:
            return self.get_previous_by_create_date()
        except Post.DoesNotExist:
            return None

    def get_next_post(self):
        # get_next_by_<필드명> 메서드
        try:
            return self.get_next_by_create_date()
        except Post.DoesNotExist:
            return None

board/views.py
from django.shortcuts import render
# django.views.generic 는 데이터를 보여주기 위한 사전에 정의된 뷰이다. 일반적으로 프로젝트에서 많이 사용되는 뷰가 있다.
from django.views.generic import ListView, DetailView, TemplateView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy

from board.models import Post

# Create your views here.
class PostList(ListView):
    model = Post
    # template_name = 'board/post_list.html'
    context_object_name = 'posts'
    # https://goo.gl/BRFiJV 페이지당 표시해야 할 객체의 수를 지정
    paginate_by = 10

class PostDetail(DetailView):
    # url의 파라미터에서 pk값을 추출하여 사용 현재 게시물을 확인
    model = Post
    context_object_name = 'post'

class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content']
    success_url = reverse_lazy('board:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(PostCreate, self).form_valid(form)

mysite/views.py
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.models import User
from django.http import JsonResponse

class HomeView(TemplateView):
    template_name = 'home.html'

class UserRegisterView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')

class UserRegisterDoneView(TemplateView):
    template_name = 'registration/register_done.html'


# get 방식
def validate_username(request):
    # HttpRequest 객체의 GET 과 POST 속성은 django.http.QueryDict 의 인스턴스입니다.
    # get()메서드는 키(여기서는 username)이 없는 경우 기본값 'None'을 반환합니다. https://goo.gl/wtA6KN
    username = request.GET.get('username', None)
    data = {
        # <필드명>__iexact는 대소문자를 구분하지 않고 일치하는 값을 찾는다. https://goo.gl/5XywcT
        # exists()는 쿼리셋에 결과가 있는 경우 True를 반환합니다. https://goo.gl/Vgtr2u
        'is_taken':User.objects.filter(username__iexact = username).exists()
    }
    if data['is_taken']:
        data['error_message'] = '사용자가 이미 존재합니다. 다른 이름을 입력해 주세요.'

    # data를 Json형식으로 인코딩되도록 합니다.
    return JsonResponse(data)

board/templates/board/base_board.html
{% extends "base.html" %}
{% block title %}게시판{% endblock %}
{% load staticfiles %}
{% block extra_style %}{% static "css/board.css" %}{% endblock %}
{% block content %}
<h1>게시판</h1>
<nav>
    <ul>
        <li><a href="{% url 'board:post_add' %}">쓰기</a></li>
    </ul>
</nav>
{% block content_board %}{% endblock content_board %}
{% endblock content %}

board/templates/board/post_detail.html
{% extends "board/base_board.html" %}
{% block title %}게시판 내용{% endblock %}
{% block content_board %}
<h2>{{post.title}}</h2>
<div>글쓴이: {{post.owner}} 작성:{{post.create_date}} 수정:{{post.modify_date}}</div>
<p>{{post.content}}</p>

{% if post.get_previous_post %}
<a href="{{post.get_previous_post.get_absolute_url}}">이전글</a>
{% else %}
처음
{% endif %}
{% if post.get_next_post %}
<a href="{{post.get_next_post.get_absolute_url}}">다음글</a>
{% else %}
마지막
{% endif %}
{% endblock content_board %}

board/templates/board/post_form.html
{% extends "board/base_board.html" %}
{% block title %}게시판 쓰기{% endblock %}
{% block content_board %}
<h2>쓰기</h2>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content_board %}

board/templates/board/post_list.html
{% extends "board/base_board.html" %}
{% block title %}게시판 목록{% endblock %}
{% block content_board %}
<h2>목록보기</h2>
<div>
{% for post in posts %}
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    <!-- https://goo.gl/aw2sQW 내장 템플릿 태그와 필터 -->
    <br>{{ post.owner }} {{ post.modify_date|date:"M/d"|lower }}
    {% if forloop.last == False %}
    <br>
    {% endif %}
{% endfor %}
</div>
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">이전</a>
    {% endif %}
    <!-- https://goo.gl/BRFiJV 의 Context부분 참고 -->
    <!-- https://goo.gl/cS47NK page 객체에 number -->
    {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">다음</a>
    {% endif %}
{% endblock content_board %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}장고 게시판{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static "css/base.css" %}">
    <link rel="stylesheet" href="{% block extra_style %}{% endblock %}" />
</head>

<body>
    <nav class="clearfix">
        <ul>
            <li>
                <a href="{% url 'home' %}">홈</a>
            </li>
            {% if user.is_active %}
            <li>{% firstof user.get_short_name user.get_username %}님 입장.</li>
            <li>
                <a href="{% url 'password_change' %}">비밀번호 변경</a>
            </li>
            {% if user.is_superuser %}
            <li>
                <a href="{% url 'admin:index' %}">관리자</a>
            </li>
            {% endif %}
            <li>
                <a href="{% url 'logout' %}">로그아웃</a>
            </li>
            {% else %}
            <li>환영합니다.</li>
            <li>
                <a href="{% url 'login' %}">로그인</a>
            </li>
            <li>
                <a href="{% url 'register' %}">회원가입</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    <nav class="clearfix"
        <ul>
            <li>
                <a href="{% url 'board:index' %}">게시판</a>
            </li>
        </ul>
    </nav>
    {% block content %}
    {% endblock %}

    {% block footer %}
    <div>&copy; 2017. (이름) All rights reserved.</div>{% endblock %}
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <script src="{% static 'js/app.js' %}"></script>
    {% block javascript %}{% endblock %}
</body>

</html>

templates/home.html
{% extends "base.html" %} 
{% block title %}{% endblock %}
{% load staticfiles %}
<!-- {% block extra_style %}{% static "css/home.css" %}{% endblock %} -->
{% block content %}
<div>
    홈페이지
</div>
{% endblock %}